//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Demo2 : Idemo
{
	public virtual Demo Demo
	{
		get;
		set;
	}

	public virtual void Add()
	{
		throw new System.NotImplementedException();
	}

}

